// ── Development-only mock data ────────────────────────────────────────────────
// Used automatically when Alpha Vantage returns 429 in NODE_ENV=development.
// Never referenced in production builds.
import type { StockOverview, GlobalQuote } from "./alphaVantage";

interface MockEntry {
  overview: StockOverview;
  quote: GlobalQuote;
}

/** Returns the most recent weekday (Mon–Fri) as a YYYY-MM-DD string. */
function lastWeekday(): string {
  const d = new Date();
  const day = d.getUTCDay(); // 0=Sun, 6=Sat
  if (day === 0) d.setUTCDate(d.getUTCDate() - 2); // Sun → Fri
  if (day === 6) d.setUTCDate(d.getUTCDate() - 1); // Sat → Fri
  return d.toISOString().slice(0, 10);
}

function makeQuote(
  symbol: string,
  price: number,
  prevClose: number,
  volume = "28000000"
): GlobalQuote {
  const rawChange = price - prevClose;
  const change = rawChange.toFixed(2);
  const changePct = `${((rawChange / prevClose) * 100).toFixed(2)}%`;
  return {
    "01. symbol": symbol,
    "02. open": (price * 0.998).toFixed(2),
    "03. high": (price * 1.014).toFixed(2),
    "04. low": (price * 0.987).toFixed(2),
    "05. price": price.toFixed(2),
    "06. volume": volume,
    "07. latest trading day": lastWeekday(),
    "08. previous close": prevClose.toFixed(2),
    "09. change": change,
    "10. change percent": changePct,
  };
}

const MOCK_DATA: Record<string, MockEntry> = {
  AAPL: {
    overview: {
      Symbol: "AAPL",
      Name: "Apple Inc",
      Description:
        "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. It also sells various related services including App Store, Apple Music, iCloud, and Apple TV+.",
      Exchange: "NASDAQ",
      Currency: "USD",
      Country: "USA",
      Sector: "Technology",
      Industry: "Consumer Electronics",
      Address: "One Apple Park Way, Cupertino, CA 95014, USA",
      MarketCapitalization: "3350000000000",
      RevenueTTM: "391035000000",
      GrossProfitTTM: "180683000000",
      EPS: "6.42",
      DilutedEPSTTM: "6.42",
      ProfitMargin: "0.2488",
      OperatingMarginTTM: "0.3105",
      ReturnOnEquityTTM: "1.5731",
      ReturnOnAssetsTTM: "0.2289",
      PERatio: "33.24",
      ForwardPE: "29.85",
      PEGRatio: "2.84",
      Beta: "1.24",
      "52WeekHigh": "260.10",
      "52WeekLow": "164.08",
      "50DayMovingAverage": "228.45",
      "200DayMovingAverage": "215.70",
      DividendYield: "0.0051",
      DividendPerShare: "1.00",
      AnalystTargetPrice: "247.50",
      SharesOutstanding: "15204137000",
      DebtToEquity: "None",
    },
    quote: makeQuote("AAPL", 220.82, 218.95, "52300000"),
  },

  COIN: {
    overview: {
      Symbol: "COIN",
      Name: "Coinbase Global Inc",
      Description:
        "Coinbase Global, Inc. provides financial infrastructure and technology for the crypto economy in the United States and internationally. It offers the primary financial account in the cryptoeconomy for retailers, and a marketplace with a pool of liquidity for professional traders.",
      Exchange: "NASDAQ",
      Currency: "USD",
      Country: "USA",
      Sector: "Financial Services",
      Industry: "Financial Data & Stock Exchanges",
      Address: "248 3rd St #434, Oakland, CA 94607, USA",
      MarketCapitalization: "70800000000",
      RevenueTTM: "6550000000",
      GrossProfitTTM: "5830000000",
      EPS: "10.22",
      DilutedEPSTTM: "10.22",
      ProfitMargin: "0.2830",
      OperatingMarginTTM: "0.2540",
      ReturnOnEquityTTM: "0.2412",
      ReturnOnAssetsTTM: "0.0682",
      PERatio: "27.10",
      ForwardPE: "22.40",
      PEGRatio: "1.15",
      Beta: "3.42",
      "52WeekHigh": "349.75",
      "52WeekLow": "130.42",
      "50DayMovingAverage": "271.80",
      "200DayMovingAverage": "238.55",
      DividendYield: "0",
      DividendPerShare: "0",
      AnalystTargetPrice: "330.00",
      SharesOutstanding: "253000000",
      DebtToEquity: "None",
    },
    quote: makeQuote("COIN", 281.44, 274.90, "8500000"),
  },

  TSLA: {
    overview: {
      Symbol: "TSLA",
      Name: "Tesla Inc",
      Description:
        "Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, energy generation and storage systems, and related services in the United States, China, and internationally. It operates through two segments, Automotive, and Energy Generation and Storage.",
      Exchange: "NASDAQ",
      Currency: "USD",
      Country: "USA",
      Sector: "Consumer Cyclical",
      Industry: "Auto Manufacturers",
      Address: "1 Tesla Road, Austin, TX 78725, USA",
      MarketCapitalization: "800000000000",
      RevenueTTM: "97690000000",
      GrossProfitTTM: "17455000000",
      EPS: "3.65",
      DilutedEPSTTM: "3.65",
      ProfitMargin: "0.0570",
      OperatingMarginTTM: "0.0750",
      ReturnOnEquityTTM: "0.1283",
      ReturnOnAssetsTTM: "0.0612",
      PERatio: "68.49",
      ForwardPE: "55.20",
      PEGRatio: "4.82",
      Beta: "2.34",
      "52WeekHigh": "488.54",
      "52WeekLow": "138.80",
      "50DayMovingAverage": "335.60",
      "200DayMovingAverage": "272.40",
      DividendYield: "0",
      DividendPerShare: "0",
      AnalystTargetPrice: "295.00",
      SharesOutstanding: "3197000000",
      DebtToEquity: "None",
    },
    quote: makeQuote("TSLA", 250.15, 257.88, "98400000"),
  },

  NVDA: {
    overview: {
      Symbol: "NVDA",
      Name: "NVIDIA Corporation",
      Description:
        "NVIDIA Corporation provides graphics and compute and networking solutions in the United States, Taiwan, China, and internationally. Its GPU platforms power AI training, inference, data centers, autonomous vehicles, robotics, and gaming worldwide.",
      Exchange: "NASDAQ",
      Currency: "USD",
      Country: "USA",
      Sector: "Technology",
      Industry: "Semiconductors",
      Address: "2788 San Tomas Expressway, Santa Clara, CA 95051, USA",
      MarketCapitalization: "3300000000000",
      RevenueTTM: "130497000000",
      GrossProfitTTM: "97994000000",
      EPS: "2.99",
      DilutedEPSTTM: "2.99",
      ProfitMargin: "0.5530",
      OperatingMarginTTM: "0.6160",
      ReturnOnEquityTTM: "1.2443",
      ReturnOnAssetsTTM: "0.5580",
      PERatio: "45.15",
      ForwardPE: "30.22",
      PEGRatio: "1.08",
      Beta: "1.65",
      "52WeekHigh": "153.13",
      "52WeekLow": "66.25",
      "50DayMovingAverage": "131.40",
      "200DayMovingAverage": "120.85",
      DividendYield: "0.0003",
      DividendPerShare: "0.04",
      AnalystTargetPrice: "175.00",
      SharesOutstanding: "24440000000",
      DebtToEquity: "None",
    },
    quote: makeQuote("NVDA", 135.08, 131.62, "186000000"),
  },

  META: {
    overview: {
      Symbol: "META",
      Name: "Meta Platforms Inc",
      Description:
        "Meta Platforms, Inc. engages in the development of social media apps. Its products include Facebook, Instagram, Messenger, WhatsApp, and other services. The company also develops the Quest virtual reality headset and Ray-Ban Meta smart glasses, and invests heavily in AI infrastructure.",
      Exchange: "NASDAQ",
      Currency: "USD",
      Country: "USA",
      Sector: "Technology",
      Industry: "Internet Content & Information",
      Address: "1 Meta Way, Menlo Park, CA 94025, USA",
      MarketCapitalization: "1580000000000",
      RevenueTTM: "164496000000",
      GrossProfitTTM: "133050000000",
      EPS: "23.86",
      DilutedEPSTTM: "23.86",
      ProfitMargin: "0.3870",
      OperatingMarginTTM: "0.4610",
      ReturnOnEquityTTM: "0.3824",
      ReturnOnAssetsTTM: "0.2215",
      PERatio: "25.99",
      ForwardPE: "22.30",
      PEGRatio: "1.42",
      Beta: "1.22",
      "52WeekHigh": "740.91",
      "52WeekLow": "414.50",
      "50DayMovingAverage": "625.80",
      "200DayMovingAverage": "572.30",
      DividendYield: "0.0032",
      DividendPerShare: "2.00",
      AnalystTargetPrice: "720.00",
      SharesOutstanding: "2552000000",
      DebtToEquity: "None",
    },
    quote: makeQuote("META", 620.44, 612.75, "14200000"),
  },

  MSFT: {
    overview: {
      Symbol: "MSFT",
      Name: "Microsoft Corporation",
      Description:
        "Microsoft Corporation develops and supports software, services, devices, and solutions worldwide. Its products include Windows, Office 365, Azure cloud services, LinkedIn, Xbox, and GitHub. Microsoft is a leading investor in OpenAI and is integrating AI capabilities across its product suite.",
      Exchange: "NASDAQ",
      Currency: "USD",
      Country: "USA",
      Sector: "Technology",
      Industry: "Software—Infrastructure",
      Address: "One Microsoft Way, Redmond, WA 98052, USA",
      MarketCapitalization: "3090000000000",
      RevenueTTM: "261801000000",
      GrossProfitTTM: "178632000000",
      EPS: "12.93",
      DilutedEPSTTM: "12.93",
      ProfitMargin: "0.3570",
      OperatingMarginTTM: "0.4620",
      ReturnOnEquityTTM: "0.3584",
      ReturnOnAssetsTTM: "0.1832",
      PERatio: "32.08",
      ForwardPE: "28.15",
      PEGRatio: "2.48",
      Beta: "0.90",
      "52WeekHigh": "468.35",
      "52WeekLow": "366.78",
      "50DayMovingAverage": "418.20",
      "200DayMovingAverage": "420.55",
      DividendYield: "0.0072",
      DividendPerShare: "3.00",
      AnalystTargetPrice: "500.00",
      SharesOutstanding: "7433000000",
      DebtToEquity: "None",
    },
    quote: makeQuote("MSFT", 415.32, 411.88, "21500000"),
  },

  GOOGL: {
    overview: {
      Symbol: "GOOGL",
      Name: "Alphabet Inc",
      Description:
        "Alphabet Inc. provides various products and platforms in the United States, Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America. It operates through Google Services, Google Cloud, and Other Bets segments. Products include Google Search, YouTube, Android, Chrome, Google Maps, and Gemini AI.",
      Exchange: "NASDAQ",
      Currency: "USD",
      Country: "USA",
      Sector: "Technology",
      Industry: "Internet Content & Information",
      Address: "1600 Amphitheatre Parkway, Mountain View, CA 94043, USA",
      MarketCapitalization: "2350000000000",
      RevenueTTM: "350018000000",
      GrossProfitTTM: "207984000000",
      EPS: "8.04",
      DilutedEPSTTM: "8.04",
      ProfitMargin: "0.2950",
      OperatingMarginTTM: "0.3250",
      ReturnOnEquityTTM: "0.3312",
      ReturnOnAssetsTTM: "0.1752",
      PERatio: "23.64",
      ForwardPE: "20.80",
      PEGRatio: "1.38",
      Beta: "1.06",
      "52WeekHigh": "208.70",
      "52WeekLow": "140.53",
      "50DayMovingAverage": "188.40",
      "200DayMovingAverage": "175.60",
      DividendYield: "0.0025",
      DividendPerShare: "0.80",
      AnalystTargetPrice: "220.00",
      SharesOutstanding: "12351000000",
      DebtToEquity: "None",
    },
    quote: makeQuote("GOOGL", 190.02, 187.44, "27800000"),
  },

  AMZN: {
    overview: {
      Symbol: "AMZN",
      Name: "Amazon.com Inc",
      Description:
        "Amazon.com, Inc. engages in the retail sale of consumer products, advertising, and subscriptions service through online and physical stores in North America and internationally. It operates through three segments: North America, International, and Amazon Web Services (AWS).",
      Exchange: "NASDAQ",
      Currency: "USD",
      Country: "USA",
      Sector: "Consumer Cyclical",
      Industry: "Internet Retail",
      Address: "410 Terry Avenue North, Seattle, WA 98109, USA",
      MarketCapitalization: "2380000000000",
      RevenueTTM: "637959000000",
      GrossProfitTTM: "285259000000",
      EPS: "5.53",
      DilutedEPSTTM: "5.53",
      ProfitMargin: "0.0980",
      OperatingMarginTTM: "0.1070",
      ReturnOnEquityTTM: "0.2332",
      ReturnOnAssetsTTM: "0.0824",
      PERatio: "40.69",
      ForwardPE: "33.20",
      PEGRatio: "1.62",
      Beta: "1.17",
      "52WeekHigh": "242.52",
      "52WeekLow": "151.61",
      "50DayMovingAverage": "222.80",
      "200DayMovingAverage": "206.40",
      DividendYield: "0",
      DividendPerShare: "0",
      AnalystTargetPrice: "260.00",
      SharesOutstanding: "10580000000",
      DebtToEquity: "None",
    },
    quote: makeQuote("AMZN", 225.18, 222.65, "38900000"),
  },

  NVO: {
    overview: {
      Symbol: "NVO",
      Name: "Novo Nordisk A/S",
      Description:
        "Novo Nordisk A/S, a healthcare company, engages in the research, development, manufacture, and marketing of pharmaceutical products worldwide. It operates in two segments, Diabetes and Obesity care, and Rare Disease. The company offers products including Ozempic and Wegovy for diabetes and obesity treatment.",
      Exchange: "NYSE",
      Currency: "USD",
      Country: "Denmark",
      Sector: "Healthcare",
      Industry: "Drug Manufacturers—General",
      Address: "Novo Alle 1, Bagsvaerd 2880, Denmark",
      MarketCapitalization: "420000000000",
      RevenueTTM: "38100000000",
      GrossProfitTTM: "32200000000",
      EPS: "3.51",
      DilutedEPSTTM: "3.51",
      ProfitMargin: "0.3140",
      OperatingMarginTTM: "0.4050",
      ReturnOnEquityTTM: "0.8724",
      ReturnOnAssetsTTM: "0.2980",
      PERatio: "27.07",
      ForwardPE: "20.40",
      PEGRatio: "1.24",
      Beta: "0.44",
      "52WeekHigh": "138.92",
      "52WeekLow": "71.56",
      "50DayMovingAverage": "88.55",
      "200DayMovingAverage": "99.80",
      DividendYield: "0.0168",
      DividendPerShare: "1.60",
      AnalystTargetPrice: "115.00",
      SharesOutstanding: "4438000000",
      DebtToEquity: "None",
    },
    quote: makeQuote("NVO", 95.08, 93.75, "6400000"),
  },

  CRSP: {
    overview: {
      Symbol: "CRSP",
      Name: "CRISPR Therapeutics AG",
      Description:
        "CRISPR Therapeutics AG, a gene editing company, focuses on developing transformative gene-based medicines for serious diseases. It has developed a proprietary CRISPR/Cas9 gene-editing platform and has a portfolio of therapeutic programs in hemoglobinopathies, oncology, regenerative medicine, and rare diseases.",
      Exchange: "NASDAQ",
      Currency: "USD",
      Country: "Switzerland",
      Sector: "Healthcare",
      Industry: "Biotechnology",
      Address: "Baarerstrasse 14, Zug 6300, Switzerland",
      MarketCapitalization: "3600000000",
      RevenueTTM: "135000000",
      GrossProfitTTM: "134000000",
      EPS: "-8.25",
      DilutedEPSTTM: "-8.25",
      ProfitMargin: "-1.2340",
      OperatingMarginTTM: "-3.0200",
      ReturnOnEquityTTM: "-0.1842",
      ReturnOnAssetsTTM: "-0.1115",
      PERatio: "None",
      ForwardPE: "None",
      PEGRatio: "None",
      Beta: "1.88",
      "52WeekHigh": "76.54",
      "52WeekLow": "29.38",
      "50DayMovingAverage": "42.80",
      "200DayMovingAverage": "52.40",
      DividendYield: "0",
      DividendPerShare: "0",
      AnalystTargetPrice: "68.00",
      SharesOutstanding: "80000000",
      DebtToEquity: "None",
    },
    quote: makeQuote("CRSP", 45.22, 44.10, "1200000"),
  },

  IREN: {
    overview: {
      Symbol: "IREN",
      Name: "Iris Energy Limited",
      Description:
        "Iris Energy Limited develops, owns, and operates data centers powered by renewable energy in North America and Australia. The company mines Bitcoin and provides high-performance computing services for artificial intelligence workloads.",
      Exchange: "NASDAQ",
      Currency: "USD",
      Country: "Australia",
      Sector: "Technology",
      Industry: "Computer Hardware",
      Address: "Level 12, 10 Carrington Street, Sydney NSW 2000, Australia",
      MarketCapitalization: "900000000",
      RevenueTTM: "195000000",
      GrossProfitTTM: "95000000",
      EPS: "-1.15",
      DilutedEPSTTM: "-1.15",
      ProfitMargin: "-0.5200",
      OperatingMarginTTM: "-0.3800",
      ReturnOnEquityTTM: "-0.2240",
      ReturnOnAssetsTTM: "-0.0844",
      PERatio: "None",
      ForwardPE: "None",
      PEGRatio: "None",
      Beta: "2.85",
      "52WeekHigh": "18.85",
      "52WeekLow": "5.42",
      "50DayMovingAverage": "11.20",
      "200DayMovingAverage": "10.45",
      DividendYield: "0",
      DividendPerShare: "0",
      AnalystTargetPrice: "16.50",
      SharesOutstanding: "75000000",
      DebtToEquity: "None",
    },
    quote: makeQuote("IREN", 12.04, 11.68, "4800000"),
  },

  OKLO: {
    overview: {
      Symbol: "OKLO",
      Name: "Oklo Inc",
      Description:
        "Oklo Inc. designs and develops advanced fission power plants to provide clean, reliable, and affordable energy. The company is developing the Aurora Powerhouse, a fast fission power plant designed to generate 15 megawatts of electrical power. Oklo targets data centers and AI infrastructure as primary customers.",
      Exchange: "NYSE",
      Currency: "USD",
      Country: "USA",
      Sector: "Utilities",
      Industry: "Utilities—Renewable",
      Address: "3190 Coronado Drive, Santa Clara, CA 95054, USA",
      MarketCapitalization: "3100000000",
      RevenueTTM: "500000",
      GrossProfitTTM: "0",
      EPS: "-1.42",
      DilutedEPSTTM: "-1.42",
      ProfitMargin: "None",
      OperatingMarginTTM: "None",
      ReturnOnEquityTTM: "-0.3840",
      ReturnOnAssetsTTM: "-0.2112",
      PERatio: "None",
      ForwardPE: "None",
      PEGRatio: "None",
      Beta: "1.95",
      "52WeekHigh": "58.00",
      "52WeekLow": "7.22",
      "50DayMovingAverage": "24.80",
      "200DayMovingAverage": "21.40",
      DividendYield: "0",
      DividendPerShare: "0",
      AnalystTargetPrice: "30.00",
      SharesOutstanding: "141000000",
      DebtToEquity: "None",
    },
    quote: makeQuote("OKLO", 22.18, 21.50, "3500000"),
  },

  RKLB: {
    overview: {
      Symbol: "RKLB",
      Name: "Rocket Lab USA Inc",
      Description:
        "Rocket Lab USA, Inc. provides launch services and space systems solutions. Its products include the Electron small orbital launch vehicle, the Neutron medium-to-heavy lift launch vehicle under development, and a range of spacecraft components and satellite platforms sold to commercial and government customers.",
      Exchange: "NASDAQ",
      Currency: "USD",
      Country: "USA",
      Sector: "Industrials",
      Industry: "Aerospace & Defense",
      Address: "3881 McGowen Street, Long Beach, CA 90808, USA",
      MarketCapitalization: "11000000000",
      RevenueTTM: "400000000",
      GrossProfitTTM: "148000000",
      EPS: "-0.52",
      DilutedEPSTTM: "-0.52",
      ProfitMargin: "-0.5730",
      OperatingMarginTTM: "-0.5820",
      ReturnOnEquityTTM: "-0.2640",
      ReturnOnAssetsTTM: "-0.1088",
      PERatio: "None",
      ForwardPE: "None",
      PEGRatio: "None",
      Beta: "2.12",
      "52WeekHigh": "29.00",
      "52WeekLow": "4.52",
      "50DayMovingAverage": "21.80",
      "200DayMovingAverage": "14.25",
      DividendYield: "0",
      DividendPerShare: "0",
      AnalystTargetPrice: "26.00",
      SharesOutstanding: "500000000",
      DebtToEquity: "None",
    },
    quote: makeQuote("RKLB", 22.44, 21.88, "22600000"),
  },
};

export function getMockData(ticker: string): MockEntry | null {
  return MOCK_DATA[ticker.toUpperCase()] ?? null;
}
