import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: "Athena investment disclaimer — important information about the nature of AI-generated analysis.",
};

export default function DisclaimerPage() {
  return (
    <div className="relative flex-1 bg-black flex flex-col">
      <header className="relative z-10 flex items-center justify-between px-4 md:px-8 py-4 border-b border-[#1a1a1a]">
        <Link
          href="/"
          className="text-gold-gradient font-bold tracking-widest hover:opacity-80 transition-opacity"
          style={{ fontFamily: "'Cinzel', serif", fontSize: "1.1rem" }}
        >
          ATHENA
        </Link>
        <Link
          href="/"
          className="text-[11px] text-[#666] hover:text-[#d4a017] tracking-widest uppercase font-medium transition-colors duration-200"
        >
          ← Home
        </Link>
      </header>

      <main className="relative z-10 flex-1 w-full max-w-3xl mx-auto px-6 py-12">
        <h1
          className="text-white text-3xl font-bold mb-2 tracking-tight"
          style={{ fontFamily: "'Cinzel', serif" }}
        >
          Investment Disclaimer
        </h1>
        <p className="text-[#555] text-sm mb-10 tracking-widest uppercase">Last updated: March 2026</p>

        <div className="space-y-8 text-[#aaa] text-sm leading-7">
          <section>
            <h2 className="text-white text-base font-semibold mb-3 tracking-wide">Not Financial Advice</h2>
            <p>All analysis, verdicts, scores, and commentary provided by Athena are generated by artificial intelligence for informational purposes only. Nothing on this platform constitutes financial advice, investment recommendations, or solicitation to buy or sell any security.</p>
          </section>
          <section>
            <h2 className="text-white text-base font-semibold mb-3 tracking-wide">AI-Generated Content</h2>
            <p>Athena uses large language models (LLMs) to generate investment analysis. AI-generated content may contain errors, omissions, or outdated information. Users should independently verify all information before making any financial decisions.</p>
          </section>
          <section>
            <h2 className="text-white text-base font-semibold mb-3 tracking-wide">Past Performance</h2>
            <p>Past performance of any security or investment strategy does not guarantee future results. Investing involves risk, including the possible loss of principal.</p>
          </section>
          <section>
            <h2 className="text-white text-base font-semibold mb-3 tracking-wide">Data Accuracy</h2>
            <p>Market data displayed on Athena is sourced from third-party providers and may be delayed or inaccurate. Athena makes no representations regarding the accuracy, completeness, or timeliness of such data.</p>
          </section>
          <section>
            <h2 className="text-white text-base font-semibold mb-3 tracking-wide">Consult a Professional</h2>
            <p>Always consult a qualified and licensed financial advisor, broker, or investment professional before making any investment decision. Athena is a research tool, not a regulated financial service.</p>
          </section>
        </div>
      </main>
    </div>
  );
}
